#!/bin/bash

CONTENTS=(
  "🕐" "$(date '+%a %b %-d %H:%M:%S')"
  "🔋" "$(battery -r)" 
  "📡" "$(wifi -f '%a in %i [%r]')"
  "🔊" "$(volume)"
)

CONTENT_SIZE=$(( ${#CONTENTS[*]} ))

# https://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg
COLORS=(
  114 0
  222 0
) 
COLORS_SIZE=$(( ${#COLORS[*]} ))

CNT=0
DISPLAY=''
for i in `seq 0 2 $CONTENT_SIZE`
do
  if [ "${CONTENTS[$((i+1))]}" != "" ]; then
    DISPLAY=$( \
      echo "<DELIMITER><CONTENT>$DISPLAY" \
      | sed -e "s/<COLOR_NEXT>/,bg=colour${COLORS[$CNT]}/g"\
      | sed -e "s/<DELIMITER>/#[fg=colour<COLOR><COLOR_NEXT>]⮂#[default]/g" \
      | sed -e "s/<CONTENT>/<SPACE><ICON><SPACE><SPACE><MESSAGE><SPACE>/g" \
      | sed -e "s/<SPACE>/#[bg=colour<COLOR>] #[default]/g" \
      | sed -e "s/<ICON>/#[bg=colour<COLOR>]${CONTENTS[$((i))]}#[default]/g" \
      | sed -e "s?<MESSAGE>?#[bg=colour${COLORS[$CNT]},fg=colour${COLORS[$((CNT+1))]}]${CONTENTS[$((i+1))]}#[default]?g" \
      | sed -e "s/<COLOR>/${COLORS[$CNT]}/g" \
      )
    CNT=$(((CNT+2)%COLORS_SIZE))
  fi
done
DISPLAY=$( \
  echo $DISPLAY \
  | sed -e "s/<COLOR_NEXT>//g" \
  )

echo $DISPLAY

