#!/bin/bash

DISPLAY=''
colors=(
  208 0
  190 0
  226 0
) 
cnt=0
size=${#colors[*]}

add-content()
{

  index=`expr $cnt % $size`
  DISPLAY=$( echo $DISPLAY | sed -e "s/<__BG__>/,bg=colour${colors[$index]}/g" )
  space="#[bg=colour${colors[$index]}] #[default]" 
  delimiter="#[fg=colour${colors[$index]}<__BG__>]⮂#[default]" 
  icon="#[bg=colour${colors[$index]}]$1 #[default]" 
  message="#[bg=colour${colors[$index]},fg=colour${colors[${index+1}]}]$2#[default]" 
  content="$space$icon$space$message$space"
  DISPLAY="$delimiter$content$DISPLAY"
  cnt=`expr $cnt + 2`
}

add-content "🕐" "$(date '+%a %b %-d %H:%M:%S')"
add-content "🔋" "$(battery -r)" 
add-content "📡" "$(wifi -f '%a in %i [%r]')"
add-content "🔊" "$(volume)"
DISPLAY=$( echo $DISPLAY  | sed -e "s/<__BG__>//g" )

echo $DISPLAY

