#!/bin/bash

CONTENTS=(
  "$($HOME/.tmux/bin/dates   -f '%icon　%dates')"
  "$($HOME/.tmux/bin/ime     -f '%icon　%name')"
  "$($HOME/.tmux/bin/battery -f '%icon　%percentage% (%remain)')" 
  "$($HOME/.tmux/bin/wifi    -f '%icon　%ssid')"
  "$($HOME/.tmux/bin/volume  -f '%icon　%volume%')"
)

CONTENT_SIZE=$(( ${#CONTENTS[*]} ))

# https://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg
COLORS=(
  236 180 
  237 180 
  238 180 
  239 180 
  240 180
  241 180
) 
COLORS_SIZE=$(( ${#COLORS[*]} ))

CNT=0
DISPLAY=''
for i in `seq 0 $CONTENT_SIZE`
do
  if [ "${CONTENTS[$i]}" != "" ]; then
    DISPLAY=$( \
      echo "<DELIMITER><CONTENT>$DISPLAY" \
      | sed -e "s/<COLOR_NEXT>/,bg=colour${COLORS[$CNT]}/g"\
      | sed -e "s/<DELIMITER>/#[fg=colour<COLOR><COLOR_NEXT>]⮂#[default]/g" \
      | sed -e "s/<CONTENT>/<SPACE><MESSAGE><SPACE>/g" \
      | sed -e "s/<SPACE>/#[bg=colour<COLOR>] #[default]/g" \
      | sed -e "s?<MESSAGE>?#[bg=colour${COLORS[$CNT]},fg=colour${COLORS[$((CNT+1))]}]${CONTENTS[$((i))]}#[default]?g" \
      | sed -e "s/<COLOR>/${COLORS[$CNT]}/g" \
      )
    CNT=$(((CNT+2)%COLORS_SIZE))
  fi
done
DISPLAY=$( \
  echo $DISPLAY \
  | sed -e "s/<COLOR_NEXT>//g" \
  )

echo $DISPLAY

