[[plugins]]
repo = 'udalov/kotlin-vim' # {{{
on_ft = 'kotlin'
# }}}

[[plugins]]
repo = 'ynoca/applescript.vim' # {{{
on_ft = 'applescript'
# }}}

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
on_ft = 'julia'

[[plugins]]
repo = 'zsh-users/zsh-syntax-highlighting'
on_ft = 'zsh'

