[[plugins]]
repo = 'rhysd/unite-ruby-require.vim' # {{{
on_ft = 'ruby'
# }}}

[[plugins]]
repo = 'rhysd/vim-textobj-ruby' # {{{
on_ft = 'ruby'
# }}}

[[plugins]]
repo = 'osyo-manga/vim-monster' # {{{
on_ft = 'ruby'
hook_add = '''
    let g:monster#completion#rcodetools#backend = "async_rct_complete"
    let g:deoplete#sources#omni#input_patterns = {
    \   "ruby" : '[^. *\t]\.\w*\|\h\w*::',
    \}
'''
# }}}

[[plugins]]
repo = 'alpaca-tc/alpaca_tags' # {{{
on_ft = 'ruby'
hook_add = '''
    let g:alpaca_tags#config = {
           \ '_' : '-R --sort=yes --languages=+Ruby --languages=-js,JavaScript',
           \ 'js' : '--languages=+js',
           \ '-js' : '--languages=-js,JavaScript',
           \ 'vim' : '--languages=+Vim,vim',
           \ 'php' : '--languages=+php',
           \ '-vim' : '--languages=-Vim,vim',
           \ '-style': '--languages=-css,scss,js,JavaScript,html',
           \ 'scss' : '--languages=+scss --languages=-css',
           \ 'css' : '--languages=+css',
           \ 'java' : '--languages=+java $JAVA_HOME/src',
           \ 'ruby': '--languages=+Ruby',
           \ 'coffee': '--languages=+coffee',
           \ '-coffee': '--languages=-coffee',
           \ 'bundle': '--languages=+Ruby',
           \ }
'''
# }}}

[[plugins]]
repo = 'rhysd/unite-ruby-require.vim' # {{{
on_ft = 'ruby'
depends = ['unite.vim']
hook_add = '''

    let g:unite_source_ruby_require_cmd = expand('$HOME/.rbenv/shims/ruby')

    " key_mappings {{{
    nnoremap <SID>[unite]rb  :<C-u>Unite<CR>
    "}}}

'''
# }}}

