[[plugins]]
repo = 'twitvim/twitvim' # {{{
hook_add = '''
  let twitvim_browser_cmd = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
  let twitvim_force_ssl = 1 
  let twitvim_count = 40
  '''
# }}}

[[plugins]]
repo = 'yuratomo/w3m.vim' # {{{
hook_add = '''
  '''
# }}}

