#!/usr/bin/env ruby

require 'google_drive'

# display usage
if ARGV.empty?
  puts 'Usage: ' + File.basename(__FILE__) + ' filename'
  exit
end

# authentication
json_file = File.expand_path(Dir.glob(File.expand_path(File.dirname(__FILE__)) + '/*.json')[0])
session = GoogleDrive::Session.from_config(json_file)

ARGV.each do |arg|
  # information about uploading file
  file        = File.expand_path(arg)
  basename    = File.basename(file)
  folder_name = File.extname(file).delete('.').upcase
  folder_name = 'others' if folder_name == ''

  # list of folder name
  folders = session.files.select { |f| f.class.to_s == 'GoogleDrive::Collection' }
  folders.map!(&:title)

  # Creat a folder if it doesn't exist.
  if folders.include?(folder_name)
  else
    session.root_collection.create_subcollection(folder_name)
  end

  # Uploads a local file.
  session.upload_from_file(file, basename, convert: false)
  g_file = session.file_by_title(basename)
  g_folder = session.file_by_title(folder_name)
  g_folder.add(g_file)
  session.root_collection.remove(g_file)
  puts file + ' has been uploaded.'

  trash = File.expand_path('~/.Trash/')
  FileUtils.mv(file, trash)
end
