#!/usr/bin/osascript

on pop()
  tell application "Google Chrome"
      set frontIndex to active tab index of front window
      set sURL to get URL of tab frontIndex of front window
      close active tab of window 1
      make new window
      activate
      open location sURL
  end tell
end pop

on next()
  tell application "Google Chrome"
      set frontIndex to active tab index of front window
      set active tab index of front window to frontIndex + 1
  end tell
end next

on prev()
  tell application "Google Chrome"
      set frontIndex to active tab index of front window
      set active tab index of front window to frontIndex - 1
  end tell
end prev

on run argv
  set command to item 1 of argv
  if command = "pop" then
    pop()
  else if command = "next" then
    next()
  else if command = "prev" then
    prev()
  end if
end run
