#!/usr/bin/osascript

on pop()
  tell application "Google Chrome"
      set frontIndex to active tab index of front window
      set sURL to get URL of tab frontIndex of front window
      close active tab of window 1
      make new window
      activate
      open location sURL
  end tell
end pop

on next()
  tell application "Google Chrome"
      set frontIndex to active tab index of front window
      set numOfTabs to count of tab of front window 
      set nextIndex to (frontIndex + 1)
      if numOfTabs < nextIndex then
        set active tab index of front window to 1
      else
        set active tab index of front window to nextIndex
      end
  end tell
end next

on prev()
  tell application "Google Chrome"
      set frontIndex to active tab index of front window
      set numOfTabs  to count of tab of front window
      set nextIndex to (frontIndex - 1) mod numOfTabs
      if 1 > nextIndex then
        set active tab index of front window to numOfTabs
      else
        set active tab index of front window to nextIndex
      end
  end tell
end prev

on run argv
  set command to item 1 of argv
  if command = "pop" then
    pop()
  else if command = "next" then
    next()
  else if command = "prev" then
    prev()
  end if
end run
